In [43]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

tf.__version__

'2.0.0-beta1'

In [44]:
trainData = pd.read_csv('data/train.csv')
trainData["label"]

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [45]:
y_train = trainData['label']
np.array(y_train).shape

(42000,)

In [46]:
trainData.shape

(42000, 785)

In [47]:
# 获取数据集中的数据的值
trainData.values

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [48]:
x_train = trainData.values[:, 1:]
print(x_train.shape)
x_train

(42000, 784)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
y_train = trainData.values[:, 0]
print(y_train.shape) 
y_train

(42000,)


array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [50]:
model = keras.Sequential()
model.add(keras.layers.Dense(units=500, activation='relu'))
model.add(keras.layers.Dense(units=500, activation='relu'))
model.add(keras.layers.Dense(units=10, activation='softmax'))


In [51]:
testData = pd.read_csv('data/test.csv')
testData.values[:, 1:].shape

(28000, 783)

In [52]:
testData.values[:, 0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [53]:
# 加载数据
def load_data(): 
    print("====>>===>>===>> LoadData")
    trainData = pd.read_csv('data/train.csv')
    testData = pd.read_csv('data/test.csv')
    x_train = trainData.values[:, 1:]
    y_train = trainData.values[:, 0]
    x_test = testData.values[:, :]
    # 归一化
    x_train = x_train/255
    x_test = x_test/255
    return x_train, y_train, x_test
    pass    


In [54]:
# 降低数据维度
def data_pca(x_train, x_test, COMPONENT_NUM):
    print("====>>===>>===>> PCA ")
    pca = PCA(n_components=COMPONENT_NUM, copy=True, whiten=False)  # 创建一个 PCA 对象
    pca.fit(x_train)    # 构建 PCA 模型
    pcaXTrain = pca.transform(x_train)
    pcaXTest = pca.transform(x_test)

    return pcaXTrain, pcaXTest


In [63]:
# 训练模型    
def create_model(x_train, y_train, x_test):
    print("====>>===>>===>> TrainMoel ")
    
    # 需要定义输入层的大小，不然保存的模型也有问题
    model = keras.Sequential()
    model.add(keras.layers.Dense(units=500, input_shape=(x_train.shape[1], ), activation='relu'))
    model.add(keras.layers.Dense(units=500, activation='relu'))
    model.add(keras.layers.Dense(units=10, activation='softmax'))

    model.compile(optimizer='adam', 
                    loss='sparse_categorical_crossentropy', 
                    metrics=['accuracy'])
    # epochs：表示一共训练的周期， batch_size：把多少层组合成一个训练单元，多线程加速
    history = model.fit(x_train, y_train, epochs=10, batch_size=32)
    model.summary()
    # 测试模型
     #保存模型
    model.save('model/model1.h5')
    # 预测数据
    result = model.predict(x_test)
    print(result)
    
    return history


In [56]:
x_train, y_train, x_test = load_data()

====>>===>>===>> LoadData


In [57]:
pcax_train, pcax_test = data_pca(x_train, x_test, 0.9)

====>>===>>===>> PCA 


In [58]:
print(pcax_train.shape, pcax_test.shape)
print(pcax_test[0])

(42000, 87) (28000, 87)
[ 3.32190522 -0.46932019  3.13070354  2.45306793  1.20052657  2.0740953
  0.7346459   0.27082966 -1.24310581  0.98568907  2.56808197 -0.69164042
 -1.33896483 -0.48007285 -0.31666621 -0.85383598 -1.7598985   1.1127037
 -1.28484004 -0.65576391 -0.97138322  0.58110974  1.16467351 -1.84140247
  0.2579552  -0.46572042 -0.14093324 -0.23201418 -0.45428519 -0.67112547
  0.74915563 -0.77246594 -0.26646933  0.91617133  0.17457964  0.45339475
  0.3875669  -0.07023289 -0.27877029 -0.295251   -0.2496131  -0.58785452
 -1.09315119  0.45731992  0.25754632  0.44007646  0.77251199 -0.37837487
  0.57031196 -0.0510938   0.42303002  0.02359084 -0.56939015 -0.09385663
  0.13332239 -0.30913786  0.01091749 -0.12600315  0.44814993  0.04855498
  0.19473891 -0.74181079  0.64441837  0.04463152  0.28666107 -0.65346968
  0.26273464  0.08131494  0.27357135 -0.15527749 -1.11881189  0.19038616
 -0.37652002 -0.06293331  0.59696919 -0.01591315 -0.23493578  0.56184488
  0.29340562  0.14012564  0.0

In [64]:
hity = create_model(pcax_train, y_train, pcax_test)

====>>===>>===>> TrainMoel 
Train on 42000 samples
Epoch 1/10
42000/42000 [==============================] - 5s 117us/sample - loss: 0.1949 - accuracy: 0.9410
Epoch 2/10
42000/42000 [==============================] - 5s 111us/sample - loss: 0.0763 - accuracy: 0.9767
Epoch 3/10
42000/42000 [==============================] - 5s 118us/sample - loss: 0.0486 - accuracy: 0.9844
Epoch 4/10
42000/42000 [==============================] - 5s 116us/sample - loss: 0.0356 - accuracy: 0.9880
Epoch 5/10
42000/42000 [==============================] - 5s 115us/sample - loss: 0.0276 - accuracy: 0.9907
Epoch 6/10
42000/42000 [==============================] - 5s 127us/sample - loss: 0.0233 - accuracy: 0.9925
Epoch 7/10
42000/42000 [==============================] - 5s 122us/sample - loss: 0.0226 - accuracy: 0.9924
Epoch 8/10
42000/42000 [==============================] - 5s 117us/sample - loss: 0.0187 - accuracy: 0.9937
Epoch 9/10
42000/42000 [==============================] - 5s 116us/sample - loss: 0.0

In [ ]:
hity.history

In [ ]:
loss = hity.history['loss']
accuracy = hity.history['accuracy']
print(loss,'\n', accuracy)

In [ ]:
x = range(1, len(loss) + 1)
plt.plot(x, loss, label='training loss' )
plt.xlabel('x')
plt.ylabel('loss')
plt.show()

In [ ]:
plt.plot(x, accuracy)
plt.ylabel('P')
plt.xlabel('x')

In [ ]:
model1 = keras.models.load_model('model/model1.h5')

In [ ]:
pcax_test[0]

In [ ]:
result2 = model1.predict(pcax_test)
result2

In [ ]:
array = np.zeros((len(result2), 1))
for i in range(len(result2)):
    array[i] = np.argmax(result2[i])
    
array

In [ ]:
table = pd.DataFrame(array, columns=['label'])
table

In [ ]:
table.to_csv('data/test_label.csv')

In [ ]:
trainData = x_train * 255
testData = x_test * 255

In [ ]:
plt.plot(trainData[0])

In [ ]:
plt.show()

In [ ]:
image = np.zeros((28, 28))
for i in range(28):
    for j in range(28):
        image[i, j] = testData[0, i * 28 + j]
image

In [ ]:
fig = plt.figure('image')
plt.imshow(image)


In [ ]:
trainD = pd.read_csv('data/train.csv')
testD = pd.read_csv('data/test.csv')

In [ ]:
testData = testD.values[:, :]
image2 = np.zeros(( 28, 28))

for j in range(28):
    for c in range(28):
        image2[ j, c] = testData[0, j * 28 + c]
            
image2
            

In [ ]:
plt.figure()
plt.imshow(image2)

In [ ]:
data = pd.read_csv('data/sample_submission.csv')


In [ ]:
type(data)

In [ ]:
data.columns

In [ ]:
data.columns

In [ ]:
obj = pd.Series(np.random.randint(1, 10), index=range(1, 28000))
data1 = pd.DataFrame(obj, columns=['image'])
data1.to_csv('data/data2.csv')

In [ ]:
data3 = pd.read_csv('data/sample_submission.csv')
data3.index

In [65]:
model = keras.models.load_model('model/model1.h5')

In [66]:
result = model.predict(pcax_test)
result

array([[5.38625088e-22, 6.49936729e-21, 1.00000000e+00, ...,
        6.95204853e-13, 1.99464645e-17, 2.50900369e-26],
       [1.00000000e+00, 1.69588262e-20, 9.75422235e-19, ...,
        2.67964114e-16, 4.27192823e-21, 7.09997942e-20],
       [2.03314572e-14, 4.80355816e-12, 8.20048474e-11, ...,
        3.85860289e-07, 1.41781961e-10, 9.99994636e-01],
       ...,
       [1.55823556e-22, 2.67046197e-20, 1.05560065e-18, ...,
        1.06183879e-21, 1.18016889e-14, 3.31232499e-16],
       [8.52398881e-12, 2.86328507e-18, 2.44473764e-11, ...,
        1.04045876e-10, 1.25733703e-11, 9.99999642e-01],
       [1.05154439e-20, 6.48161861e-20, 1.00000000e+00, ...,
        1.22544534e-15, 9.02370774e-16, 4.13803160e-21]], dtype=float32)

In [68]:
test_label = np.zeros((len(result), 1))
for i in range(len(result)):
    test_label[i, 0] = np.argmax(result[i])

test_label    

array([[2.],
       [0.],
       [9.],
       ...,
       [3.],
       [9.],
       [2.]])

In [75]:
data = pd.DataFrame({'image': range(1, len(test_label) + 1), 'label': test_label[:, 0]})
data.to_csv('data/data3.csv')